### ISSUE TITLE
Multiple Actions

### ISSUE THREAD

**Issue by bexelbie** [mesozoic/gmail-yaml-filters#13]
I'd like to apply multiple labels, is there a syntax for this?  It appears I need to use a foreach loop to do it now.

**Comment by mesozoic** [comment]
Great question! Right now I've hacked it into my own configuration like this:

```yaml
from: somewhere
more:
  - label: one
  - label: two
```

Both the uploader and the XML generator will ignore any rules which don't contain any actions, so while it's not terribly pretty, the above works. I think I originally had a restriction in mind where Gmail only supported one label per filter; now I'm not so sure that's actually a constraint.

I'm going to close this issue, but I would welcome pull requests that support a simpler syntax, like:

```yaml
from: somewhere
label: [one, two]
```
