### ISSUE TITLE
Rules not generated in order

### ISSUE THREAD

**Issue by bexelbie** [mesozoic/gmail-yaml-filters#15]
I was expecting that the rules were generated in order of the yaml file.  I noticed that if my first three rules were "for_each" rules, the fourth rule, the first non-for_each rule was first in the output followed by the for_each rules.  Is this expected behavior?

**Comment by mesozoic** [comment]
Right now there's no provision for generating rules in order of appearance. I'm going to close this as a duplicate of #14 but I'd welcome patches to make this work.
