### ISSUE TITLE
Generated XML file is missing the XML declaration

### ISSUE THREAD

**Issue by KushalP** [mesozoic/gmail-yaml-filters#17]
The generated XML file is missing the XML declaration:

```xml
<?xml version='1.0' encoding='UTF-8'?>
```

This results in an error, where gmail won't allow you to import the file. Make sure the generated file includes the XML declaration.

**Comment by mesozoic** [comment]
That's interesting. I've definitely used the XML export in the past, but I've used --sync for so long that Gmail may have changed their behavior in the meantime. I agree the declaration should be included; I'll fix that now.
