### ISSUE TITLE
sync with different gmail accounts?

### ISSUE THREAD

**Issue by ak2k** [mesozoic/gmail-yaml-filters#18]
Is it possible to use the sync capability with multiple gmail accounts at the same time (e.g. work account and personal account)? For example, is there a way to pass the gmail account as a CLI parameter?

**Comment by mesozoic** [comment]
Not right now, but I would welcome pull requests! The location of the
stored credentials file is hard-coded but it should be straightforward to
make that an optional command-line parameter. (Passing the Gmail account
name itself might require a bit more work.)

**Comment by ahills** [comment]
See #32 for a possible implementation.

**Comment by mesozoic** [comment]
Thanks for the nudges, and apologies for the very delayed response. This is fixed in master.
