### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by qudade** [mesozoic/gmail-yaml-filters#22]
gmail-yaml-filters looks very interesting. Conversion of yaml into xml seems to work fine.

For the upload feature the program fails because of missing files (`client_secret.json`). I couldn't find any instructions how to create this file properly. I tried to create credentials in Google console but don't know the correct redirect URI.

How to enable these features?

Thanks!

**Comment by mesozoic** [comment]
Thanks for the feedback! It seems I left out a step in the README. I've updated it with a link to Google's documentation on creating client secrets for the Python API: https://developers.google.com/identity/protocols/oauth2/web-server#creatingcred

**Comment by qudade** [comment]
@mesozoic thanks a lot! Everything works just fine, now!
