### ISSUE TITLE
Add support for "Also apply filter to matching conversations" parameter

### ISSUE THREAD

**Issue by xeron** [mesozoic/gmail-yaml-filters#27]
Basically subj.

When updating filters, I have to go to the web UI and reapply them. Would be great to do it automatically on sync.

**Comment by mesozoic** [comment]
That would be really useful, I agree. As far as I can tell there is no Gmail API to run a filter over the inbox; the script would need to run a search, iterate over the results, and perform each action through the API. That’s certainly possible, but it’s a lot of work and a moderate risk of screwing up someone’s archived mail. I’d be happy to review patches implementing this that are well tested, but if someone finds a way to do this programmatically I’d much rather rely on Gmail to modify a user’s messages.

**Comment by xeron** [comment]
I see. There's a parameter in the UI so I thought there's already parameter in the API to do that.

**Comment by mesozoic** [comment]
I'm going to close this because I think it's unlikely we'll ever get an easy way to do this via Gmail's API, but if someone out there figures it out, I will happily reopen this and work to incorporate that flag. It would be a huge help for me.
