### ISSUE TITLE
Handle empty actions on sync or prune

### ISSUE THREAD

**Issue by jnmnus** [mesozoic/gmail-yaml-filters#28]
`gmail-yaml-filters --sync` will crash when it tries to prune a rule with an empty action.

Reproducible by:
1. Create the following rule: 
```
from: jim@example.com
label: FromJim
```
2. Run `gmail-yaml-filters --sync` to create the rule in Gmail.
3. In a web browser, load (or reload) Gmail, confirming the existence of the label `FromJim`.
4. In the web browser, click on the three dots next to `FromJim` and delete the label.
5. Go to `Settings->All Settings->Filters and Blocked Addresses`. Notice that the rule has no action.
5. Rerun `gmail-yaml-filters --sync`

Expected Results:
No errors. Ideally, the label would be recreated, the rule would be redefined, and the old rule (the one with the empty action) would be deleted.

Actual Results:
An error with a traceback:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/gmail-yaml-filters", line 33, in <module>
    sys.exit(load_entry_point('gmail-yaml-filters==0.9.4', 'console_scripts', 'gmail-yaml-filters')())
  File "/home/user/.local/lib/python3.9/site-packages/gmail_yaml_filters/main.py", line 108, in main
    prune_filters_not_in_ruleset(ruleset, service=gmail, dry_run=args.dry_run)
  File "/home/user/.local/lib/python3.9/site-packages/gmail_yaml_filters/upload.py", line 215, in prune_filters_not_in_ruleset
    print('Deleting', prunable_filter['id'], prunable_filter['criteria'], prunable_filter['action'], file=sys.stderr)
KeyError: 'action'
```

**Comment by mesozoic** [comment]
Thanks for the bug report! I've just pushed a new version with a fix for this.
